# Generated by Django 2.2.12 on 2023-06-03 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0002_ordervehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='product_description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
