# Generated by Django 4.2.1 on 2023-06-03 00:51

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0003_vehicle_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
    ]
