# Generated by Django 4.2.1 on 2023-06-03 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0004_buyer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='area',
            field=models.CharField(choices=[('C', 'Chatham'), ('LS', 'LaSalle'), ('A', 'Amherstburg'), ('L', 'Lakeshore'), ('LE', 'Leamington')], default='C', max_length=2),
        ),
    ]
