# Generated by Django 4.2.1 on 2023-06-03 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0005_alter_buyer_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='fullname',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
