# Generated by Django 4.2.1 on 2023-06-04 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0006_buyer_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='area',
            field=models.CharField(choices=[('W', 'Windsor'), ('T', 'Toronto'), ('C', 'Chatham'), ('LS', 'LaSalle'), ('A', 'Amherstburg'), ('L', 'Lakeshore'), ('LE', 'Leamington')], default='C', max_length=2),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='car_price',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
