# Generated by Django 4.2.1 on 2023-06-04 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0007_alter_buyer_area_alter_vehicle_car_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='area',
            field=models.CharField(choices=[('W', 'Windsor'), ('WA', 'Waterloo'), ('T', 'Toronto'), ('C', 'Chatham'), ('LS', 'LaSalle'), ('A', 'Amherstburg'), ('L', 'Lakeshore'), ('LE', 'Leamington')], default='C', max_length=2),
        ),
    ]
