# Generated by Django 4.2.1 on 2023-06-04 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0008_alter_buyer_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titles', models.CharField(choices=[('carsite', 'A carsite website for the buyers'), ('ecommerce', 'An ecommerce platform for online shopping'), ('blog', 'A blog website for sharing articles')], max_length=100)),
                ('text', models.TextField()),
                ('new_description_added', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptions', models.ManyToManyField(to='carapp.description')),
            ],
        ),
    ]
