# Generated by Django 4.2.1 on 2023-06-11 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0009_description_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembersName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('semester', models.PositiveIntegerField(default=3)),
            ],
        ),
    ]
