# Generated by Django 4.2.1 on 2023-06-30 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0012_alter_membersname_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membersname',
            options={'ordering': ['first_name']},
        ),
        migrations.AddField(
            model_name='vehicle',
            name='car_features',
            field=models.CharField(choices=[('Cruise Control', 'Cruise Control'), ('Audio Interface', 'Audio Interface'), ('Airbags', 'Airbags'), ('Air Conditioning', 'Air Conditioning'), ('Seat Heating', 'Seat Heating'), ('ParkAssist', 'ParkAssist'), ('Power Steering', 'Power Steering'), ('Reversing Camera', 'Reversing Camera'), ('Auto Start/Stop', 'Auto Start/Stop')], default='Airbags', max_length=300),
        ),
    ]
